env:
- RUN_FULL_CODEPOINT_TESTS=true

services:
- docker

install:
- docker pull barichello/godot-ci

script:
- docker run -v $(pwd):/src -e RUN_FULL_CODEPOINT_TESTS="${RUN_FULL_CODEPOINT_TESTS}" barichello/godot-ci godot --path /src -s addons/gut/gut_cmdln.gd
