name: Import assets
inputs:
  godot-version:
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Godot
      uses: lihop/setup-godot@v2
      with:
        version: ${{ inputs.godot-version }}
    - name: Install just
      uses: taiki-e/install-action@just
    - name: Install dev dependencies
      shell: bash
      run: just install
    - name: Import assets
      shell: bash
      run: |
        # HACK: See https://github.com/godotengine/godot-proposals/issues/1362.
        (for i in {1..4}; do godot --editor --headless & sleep 5 && .github/actions/import-assets/monitor_import.sh; done) || true
