services:
  javascript:
    build: ../docker
    user: ${UID_GID}
    volumes:
      - ./godot:/src
    command:
      - /bin/bash
      - -c
      - |
        cd src
        scons platform=javascript tools=no gdnative_enabled=yes target=$${TARGET} -j$$(nproc)
