# Site settings.
title: GodotXterm
email: godotxterm@leroy.geek.nz
description: Terminal emulator for the Godot game engine.
github_username: lihop

# Build settings.
remote_theme: just-the-docs/just-the-docs

# Just-the-docs settings.
color_scheme: dark
logo: /media/logo.png
